src/Entity/EtatProduit.php
<?php

namespace App\Entity;

use App\Repository\EtatProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtatProduitRepository::class)]
class EtatProduit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 25)]
    private $nom_etat;

    #[ORM\OneToMany(mappedBy: 'etat_produit', targetEntity: Produit::class)]
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEtat(): ?string
    {
        return $this->nom_etat;
    }

    public function setNomEtat(string $nom_etat): self
    {
        $this->nom_etat = $nom_etat;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setEtatProduit($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getEtatProduit() === $this) {
                $produit->setEtatProduit(null);
            }
        }

        return $this;
    }
}

src/Entity/GenreProduit.php
<?php

namespace App\Entity;

use App\Repository\GenreProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GenreProduitRepository::class)]
class GenreProduit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 25, nullable: true)]
    private $nom_genre;

    #[ORM\ManyToMany(targetEntity: Produit::class, mappedBy: 'genre_produit')]
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomGenre(): ?string
    {
        return $this->nom_genre;
    }

    public function setNomGenre(?string $nom_genre): self
    {
        $this->nom_genre = $nom_genre;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->addGenreProduit($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeGenreProduit($this);
        }

        return $this;
    }
}

src/Entity/LangueProduit.php
<?php

namespace App\Entity;

use App\Repository\LangueProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LangueProduitRepository::class)]
class LangueProduit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 25)]
    private $nom_langue;

    #[ORM\ManyToMany(targetEntity: Produit::class, mappedBy: 'langue_produit')]
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomLangue(): ?string
    {
        return $this->nom_langue;
    }

    public function setNomLangue(string $nom_langue): self
    {
        $this->nom_langue = $nom_langue;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->addLangueProduit($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeLangueProduit($this);
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $nom_produit;

    #[ORM\Column(type: 'text')]
    private $description_produit;

    #[ORM\Column(type: 'string', length: 255)]
    private $image_produit;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $nb_manette_produit;

    #[ORM\Column(type: 'boolean')]
    private $branchement_produit;

    #[ORM\Column(type: 'boolean')]
    private $boite_produit;

    #[ORM\Column(type: 'boolean')]
    private $notice_produit;

    #[ORM\Column(type: 'integer')]
    private $prix_produit;

    #[ORM\ManyToMany(targetEntity: GenreProduit::class, inversedBy: 'produits')]
    private $genre_produit;

    #[ORM\ManyToMany(targetEntity: LangueProduit::class, inversedBy: 'produits')]
    private $langue_produit;

    #[ORM\ManyToOne(targetEntity: RegionProduit::class, inversedBy: 'produits')]
    private $region_produit;

    #[ORM\ManyToOne(targetEntity: EtatProduit::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private $etat_produit;

    #[ORM\ManyToOne(targetEntity: CategorieProduit::class, inversedBy: 'produits')]
    private $categorie_produit;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: LigneCommande::class)]
    private $ligneCommandes;

    public function __construct()
    {
        $this->genre_produit = new ArrayCollection();
        $this->langue_produit = new ArrayCollection();
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): self
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getDescriptionProduit(): ?string
    {
        return $this->description_produit;
    }

    public function setDescriptionProduit(string $description_produit): self
    {
        $this->description_produit = $description_produit;

        return $this;
    }

    public function getImageProduit(): ?string
    {
        return $this->image_produit;
    }

    public function setImageProduit(string $image_produit): self
    {
        $this->image_produit = $image_produit;

        return $this;
    }

    public function getNbManetteProduit(): ?int
    {
        return $this->nb_manette_produit;
    }

    public function setNbManetteProduit(?int $nb_manette_produit): self
    {
        $this->nb_manette_produit = $nb_manette_produit;

        return $this;
    }

    public function getBranchementProduit(): ?bool
    {
        return $this->branchement_produit;
    }

    public function setBranchementProduit(bool $branchement_produit): self
    {
        $this->branchement_produit = $branchement_produit;

        return $this;
    }

    public function getBoiteProduit(): ?bool
    {
        return $this->boite_produit;
    }

    public function setBoiteProduit(bool $boite_produit): self
    {
        $this->boite_produit = $boite_produit;

        return $this;
    }

    public function getNoticeProduit(): ?bool
    {
        return $this->notice_produit;
    }

    public function setNoticeProduit(bool $notice_produit): self
    {
        $this->notice_produit = $notice_produit;

        return $this;
    }

    public function getPrixProduit(): ?int
    {
        return $this->prix_produit;
    }

    public function setPrixProduit(int $prix_produit): self
    {
        $this->prix_produit = $prix_produit;

        return $this;
    }

    /**
     * @return Collection|GenreProduit[]
     */
    public function getGenreProduit(): Collection
    {
        return $this->genre_produit;
    }

    public function addGenreProduit(GenreProduit $genreProduit): self
    {
        if (!$this->genre_produit->contains($genreProduit)) {
            $this->genre_produit[] = $genreProduit;
        }

        return $this;
    }

    public function removeGenreProduit(GenreProduit $genreProduit): self
    {
        $this->genre_produit->removeElement($genreProduit);

        return $this;
    }

    /**
     * @return Collection|LangueProduit[]
     */
    public function getLangueProduit(): Collection
    {
        return $this->langue_produit;
    }

    public function addLangueProduit(LangueProduit $langueProduit): self
    {
        if (!$this->langue_produit->contains($langueProduit)) {
            $this->langue_produit[] = $langueProduit;
        }

        return $this;
    }

    public function removeLangueProduit(LangueProduit $langueProduit): self
    {
        $this->langue_produit->removeElement($langueProduit);

        return $this;
    }

    public function getRegionProduit(): ?RegionProduit
    {
        return $this->region_produit;
    }

    public function setRegionProduit(?RegionProduit $region_produit): self
    {
        $this->region_produit = $region_produit;

        return $this;
    }

    public function getEtatProduit(): ?EtatProduit
    {
        return $this->etat_produit;
    }

    public function setEtatProduit(?EtatProduit $etat_produit): self
    {
        $this->etat_produit = $etat_produit;

        return $this;
    }

    public function getCategorieProduit(): ?CategorieProduit
    {
        return $this->categorie_produit;
    }

    public function setCategorieProduit(?CategorieProduit $categorie_produit): self
    {
        $this->categorie_produit = $categorie_produit;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setProduit($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getProduit() === $this) {
                $ligneCommande->setProduit(null);
            }
        }

        return $this;
    }
}

src/Entity/RegionProduit.php
<?php

namespace App\Entity;

use App\Repository\RegionProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RegionProduitRepository::class)]
class RegionProduit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 25)]
    private $nom_region;

    #[ORM\OneToMany(mappedBy: 'region_produit', targetEntity: Produit::class)]
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomRegion(): ?string
    {
        return $this->nom_region;
    }

    public function setNomRegion(string $nom_region): self
    {
        $this->nom_region = $nom_region;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setRegionProduit($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getRegionProduit() === $this) {
                $produit->setRegionProduit(null);
            }
        }

        return $this;
    }
}

templates/produit/index.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}Produits!{% endblock %}

{% block body %}
<!-- baseAdmin.html.twig à créer-->
<link rel="stylesheet" href="{{ asset('css/style.css') }}"> <!-- base css à l'arrache-->
<div class="row"> <!-- On affichera les messages d'erreurs-->
  <div class="col-8 offset-2">
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="flash-{{ label }} bg-{{ label }} text-light p-3 mb-5 rounded">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}
  </div>
</div>

<h1 class="pb-5">Liste des produits</h1>

<table class="table text-center table-hover table-sm" id="table">
    <thead>
        <tr>
            <th>N°</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Image</th>
            <th>Manette(s)</th>
            <th>Branchements</th>
            <th>Boite</th>
            <th>Notice</th>
            <th>Prix</th>
            <th>Région</th>
            <th>État</th>
            <th>Catégorie</th>
            <th>Genre</th>
            <th>Langue</th>
        </tr>
    </thead>
    <tbody>
      {% for produit in produits %}
          <tr>
            <!-- Partie Produit -->
            <td class="align-middle">{{ loop.index }}</td> <!--  -->
            <td class="align-middle">{{ produit.nomProduit }}</td><!-- Nom  -->
            <td class="align-middle">{{ produit.descriptionProduit }}</td><!-- Description -->
            <td class="align-middle" id="produit-image"><img src="{{ asset('img/produits/' ~ produit.imageProduit) }}" class="card-img-top" alt="Photo principale {{produit.nomProduit}}"></td>
            <td class="align-middle">{{ produit.nbManetteProduit }}</td><!-- Nb. Manettes -->

            {% if produit.branchementProduit == false %}
            <td class="align-middle"> Non </td>
            {% else %}
            <td class="align-middle"> Inclue </td><!-- Branchements -->
            {% endif %}

            {% if produit.boiteProduit == false %}
            <td class="align-middle"> Non </td>
            {% else %}
            <td class="align-middle"> Incluse </td><!-- Branchements -->
            {% endif %}

            {% if produit.noticeProduit == false %}
            <td class="align-middle"> Non </td>
            {% else %}
            <td class="align-middle"> Incluse </td><!-- Branchements -->
            {% endif %}

            <td class="align-middle">{{ produit.prixProduit }}</td><!-- Prix -->

            <td class="align-middle">{{ produit.regionProduit.nomRegion }}</td> <!-- Région -->

            <td class="align-middle">{{ produit.etatProduit.nomEtat }}</td> <!-- État -->

            <td class="align-middle">{{ produit.categorieProduit.nomCategorie }}</td> <!-- Catégorie -->

            <td class="align-middle">
            {% for genre in produit.genreProduit %}
                <p>{{ genre.nomGenre }}</p>
            {% endfor %}
            </td>

            <td class="align-middle">
            {% for langue in produit.langueProduit %} <!-- Pour chaque langue présente dans la liste LangueProduit -->
                <p>{{ langue.nomLangue }}</p> <!-- Récupérer le nom de la langue-->
                <!-- Note, la liaison entre les relations est bien automatique faite avec Doctrine\..\..\ArrayCollection -->
            {% endfor %}
            </td>

            <td class="align-middle">
              <a href="{{ path( 'produit_update', {'id': produit.id} ) }}" class="text-primary"><i class="fas fa-pen-square"></i></a>
              <a href="{{ path( 'produit_delete', {'id': produit.id} ) }}" class="text-danger"><i class="fas fa-trash-alt"></i></a>
            </td>
          </tr>
      {% endfor %}

    </tbody>
</table>

<div class="d-flex justify-content-end my-5">
    <a href="{{ path('produit_create') }}" class="btn btn-success">Ajouter un Produit</a>
</div>
{% endblock %}

templates/produit/produitForm.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

  {{ form_start(produitForm) }}

  <div class="row">
    <div class="col-9">
      {{ form_row(produitForm.nomProduit, {'label': 'Titre'}) }}
    </div>
     <div class="col-3">
       {{ form_row(produitForm.categorieProduit, {'label': 'Catégorie du produits'}) }}
    </div>
  </div>

  <div class="col-12">
     {{ form_row(produitForm.descriptionProduit, {'label': 'Description'}) }}
  </div>

  <div class="row">
    <div class="col-12">
        <h2>Caractéristiques importantes</h2>
    </div>
    <div class="col-3">
       {{ form_row(produitForm.genreProduit, {
          'label': 'Genre (facultatif pour les consoles)',
          'label_attr': {
            'class': 'py-0'}
          }
        ) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.langueProduit, {'label': 'Langue(s)'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.regionProduit, {'label': 'Region'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.etatProduit, {'label': 'Etat Général'}) }}
    </div>
  </div>

  <div class="row">
    <h2>Détails en plus</h2>
    <div class="col-3">
       {{ form_row(produitForm.nbManetteProduit, {'label': 'Nombre de manettes'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.branchementProduit, {'label': 'Branchements'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.boiteProduit, {'label': 'Boîte'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.noticeProduit, {'label': 'Notice'}) }}
    </div>
  </div>

  <div class="row">
    <div class="col-6">
         {{ form_row(produitForm.prixProduit, {'label': 'Prix (€)'}) }}
    </div>
    <div class="col-6">
         {{ form_row(produitForm.imageProduit, {'label': 'Image du produit'}) }}
    </div>
  </div>

  <div class="col-12 d-flex justify-content-end">
    <a href="{{ path('admin_produit_index') }}" class="btn btn-danger m-3">Annuler</a>
    <button class="btn btn-success m-3">Créer</button>
  </div>

  {{ form_end(produitForm) }}

{% endblock %}

templates/produit/produitUpdateForm.html.twig
{% extends 'baseAdmin.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

  {{ form_start(produitForm) }}

  <div class="row">
    <div class="col-9">
      {{ form_row(produitForm.nomProduit, {'label': 'Titre'}) }}
    </div>
     <div class="col-3">
       {{ form_row(produitForm.categorieProduit, {'label': 'Catégorie du produits'}) }}
    </div>
  </div>

  <div class="col-12">
     {{ form_row(produitForm.descriptionProduit, {'label': 'Description'}) }}
  </div>

  <div class="row">
    <div class="col-12">
        <h2>Caractéristiques importantes</h2>
    </div>
    <div class="col-3">
       {{ form_row(produitForm.genreProduit, {
          'label': 'Genre (facultatif pour les consoles)',
          'label_attr': {
            'class': 'py-0'}
          }
        ) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.langueProduit, {'label': 'Langue(s)'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.regionProduit, {'label': 'Region'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.etatProduit, {'label': 'Etat Général'}) }}
    </div>
  </div>

  <div class="row">
    <h2>Détails en plus</h2>
    <div class="col-3">
       {{ form_row(produitForm.nbManetteProduit, {'label': 'Nombre de manettes'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.branchementProduit, {'label': 'Branchements'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.boiteProduit, {'label': 'Boîte'}) }}
    </div>
    <div class="col-3">
         {{ form_row(produitForm.noticeProduit, {'label': 'Notice'}) }}
    </div>
  </div>

  <div class="row">
    <div class="col-6">
         {{ form_row(produitForm.prixProduit, {'label': 'Prix (€)'}) }}
    </div>
    <div class="col-6">
         {{ form_row(produitForm.imageProduit, {'label': 'Image du produit'}) }}
    </div>
  </div>

  <div class="col-12 d-flex justify-content-end">
    <a href="{{ path('admin_produit_index') }}" class="btn btn-danger m-3">Annuler</a>
    <button class="btn btn-success m-3">Créer</button>
  </div>

  {{ form_end(produitForm) }}

{% endblock %}